package com.example.backend.repository;

import com.example.backend.entity.CustomerDisciplinaryRecord;
import com.example.backend.entity.enums.ViolationAction;
import com.example.backend.entity.enums.ViolationSeverity;
import com.example.backend.entity.enums.ViolationType;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Repository for CustomerDisciplinaryRecord entity
 * Replaces CustomerViolationRepository and CustomerSuspensionHistoryRepository
 */
@Repository
public interface CustomerDisciplinaryRecordRepository extends JpaRepository<CustomerDisciplinaryRecord, String> {

    /**
     * Find all records for a specific customer
     */
    List<CustomerDisciplinaryRecord> findByCustomerUserIdOrderByCreatedAtDesc(String customerId);

    /**
     * Find all records by customer entity
     */
    List<CustomerDisciplinaryRecord> findByCustomerOrderByCreatedAtDesc(com.example.backend.entity.Customer customer);

    /**
     * Count unresolved violations by customer entity
     */
    @Query("SELECT COUNT(cdr) FROM CustomerDisciplinaryRecord cdr " +
           "WHERE cdr.customer = :customer AND cdr.resolved = :isResolved")
    long countByCustomerAndIsResolved(
            @Param("customer") com.example.backend.entity.Customer customer,
            @Param("isResolved") boolean isResolved
    );

    /**
     * Find all records for a customer (paginated)
     */
    Page<CustomerDisciplinaryRecord> findByCustomerUserId(String customerId, Pageable pageable);

    /**
     * Find unresolved violations for a customer
     */
    List<CustomerDisciplinaryRecord> findByCustomerUserIdAndResolvedFalseOrderByCreatedAtDesc(String customerId);

    /**
     * Find records by violation type
     */
    Page<CustomerDisciplinaryRecord> findByViolationType(ViolationType violationType, Pageable pageable);

    /**
     * Find records by severity
     */
    Page<CustomerDisciplinaryRecord> findBySeverity(ViolationSeverity severity, Pageable pageable);

    /**
     * Find records by action taken
     */
    Page<CustomerDisciplinaryRecord> findByActionTaken(ViolationAction actionTaken, Pageable pageable);

    /**
     * Find currently suspended customers
     */
    @Query("SELECT cdr FROM CustomerDisciplinaryRecord cdr WHERE cdr.suspendedUntil IS NOT NULL " +
           "AND cdr.suspendedUntil > :now AND cdr.reinstatedAt IS NULL AND cdr.resolved = false")
    List<CustomerDisciplinaryRecord> findCurrentlySuspended(@Param("now") LocalDateTime now);

    /**
     * Find expired suspensions (should be reinstated)
     */
    @Query("SELECT cdr FROM CustomerDisciplinaryRecord cdr WHERE cdr.suspendedUntil IS NOT NULL " +
           "AND cdr.suspendedUntil <= :now AND cdr.reinstatedAt IS NULL AND cdr.resolved = false")
    List<CustomerDisciplinaryRecord> findExpiredSuspensions(@Param("now") LocalDateTime now);

    /**
     * Count violations by customer and type
     */
    long countByCustomerUserIdAndViolationType(String customerId, ViolationType violationType);

    /**
     * Count unresolved violations by customer
     */
    long countByCustomerUserIdAndResolvedFalse(String customerId);

    /**
     * Find violations within time range
     */
    @Query("SELECT cdr FROM CustomerDisciplinaryRecord cdr WHERE cdr.customer.userId = :customerId " +
           "AND cdr.createdAt BETWEEN :startDate AND :endDate ORDER BY cdr.createdAt DESC")
    List<CustomerDisciplinaryRecord> findByCustomerAndDateRange(
            @Param("customerId") String customerId,
            @Param("startDate") LocalDateTime startDate,
            @Param("endDate") LocalDateTime endDate
    );

    /**
     * Find auto-generated records pending admin review
     */
    @Query("SELECT cdr FROM CustomerDisciplinaryRecord cdr WHERE cdr.autoGenerated = true " +
           "AND cdr.reviewedByAdmin IS NULL AND cdr.actionTaken = :action")
    List<CustomerDisciplinaryRecord> findAutoGeneratedPendingReview(@Param("action") ViolationAction action);

    /**
     * Find auto-generated records pending admin review (paginated)
     */
    @Query("SELECT cdr FROM CustomerDisciplinaryRecord cdr WHERE cdr.autoGenerated = true " +
           "AND cdr.reviewedByAdmin IS NULL AND cdr.actionTaken = :action ORDER BY cdr.createdAt DESC")
    Page<CustomerDisciplinaryRecord> findAutoGeneratedPendingReviewPaged(@Param("action") ViolationAction action, Pageable pageable);

    /**
     * Find suspension history for a customer
     */
    @Query("SELECT cdr FROM CustomerDisciplinaryRecord cdr WHERE cdr.customer.userId = :customerId " +
           "AND (cdr.actionTaken = com.example.backend.entity.enums.ViolationAction.TEMPORARY_SUSPENSION " +
           "OR cdr.actionTaken = com.example.backend.entity.enums.ViolationAction.PERMANENT_BAN) " +
           "ORDER BY cdr.createdAt DESC")
    List<CustomerDisciplinaryRecord> findSuspensionHistory(@Param("customerId") String customerId);

    /**
     * Find suspension history for a customer (paginated)
     */
    @Query("SELECT cdr FROM CustomerDisciplinaryRecord cdr WHERE cdr.customer.userId = :customerId " +
           "AND (cdr.actionTaken = com.example.backend.entity.enums.ViolationAction.TEMPORARY_SUSPENSION " +
           "OR cdr.actionTaken = com.example.backend.entity.enums.ViolationAction.PERMANENT_BAN) " +
           "ORDER BY cdr.createdAt DESC")
    Page<CustomerDisciplinaryRecord> findSuspensionHistoryPaged(@Param("customerId") String customerId, Pageable pageable);

    /**
     * Count suspensions for a customer
     */
    @Query("SELECT COUNT(cdr) FROM CustomerDisciplinaryRecord cdr WHERE cdr.customer.userId = :customerId " +
           "AND (cdr.actionTaken = com.example.backend.entity.enums.ViolationAction.TEMPORARY_SUSPENSION " +
           "OR cdr.actionTaken = com.example.backend.entity.enums.ViolationAction.PERMANENT_BAN)")
    long countSuspensions(@Param("customerId") String customerId);

    /**
     * Find records by reference
     */
    List<CustomerDisciplinaryRecord> findByReferenceIdAndReferenceType(String referenceId, String referenceType);

    /**
     * Statistics: Count by violation type
     */
    @Query("SELECT cdr.violationType, COUNT(cdr) FROM CustomerDisciplinaryRecord cdr " +
           "GROUP BY cdr.violationType ORDER BY COUNT(cdr) DESC")
    List<Object[]> countByViolationType();

    /**
     * Statistics: Count by severity
     */
    @Query("SELECT cdr.severity, COUNT(cdr) FROM CustomerDisciplinaryRecord cdr " +
           "GROUP BY cdr.severity ORDER BY COUNT(cdr) DESC")
    List<Object[]> countBySeverity();

    /**
     * Count violations by customer, type, and after date
     */
    @Query("SELECT COUNT(cdr) FROM CustomerDisciplinaryRecord cdr " +
           "WHERE cdr.customer.userId = :customerId " +
           "AND cdr.violationType = :violationType " +
           "AND cdr.createdAt > :afterDate")
    long countByCustomerUserIdAndViolationTypeAndCreatedAtAfter(
            @Param("customerId") String customerId,
            @Param("violationType") ViolationType violationType,
            @Param("afterDate") LocalDateTime afterDate
    );

    /**
     * Count violations by customer, action, and after date
     */
    @Query("SELECT COUNT(cdr) FROM CustomerDisciplinaryRecord cdr " +
           "WHERE cdr.customer.userId = :customerId " +
           "AND cdr.actionTaken = :actionTaken " +
           "AND cdr.createdAt > :afterDate")
    long countByCustomerUserIdAndActionTakenAndCreatedAtAfter(
            @Param("customerId") String customerId,
            @Param("actionTaken") ViolationAction actionTaken,
            @Param("afterDate") LocalDateTime afterDate
    );

    /**
     * Find unresolved violations by customer
     */
    List<CustomerDisciplinaryRecord> findByCustomerUserIdAndResolvedFalse(String customerId);

    /**
     * Find currently suspended records for a specific customer
     */
    @Query("SELECT cdr FROM CustomerDisciplinaryRecord cdr " +
           "WHERE cdr.customer.userId = :customerId " +
           "AND cdr.suspendedUntil IS NOT NULL " +
           "AND cdr.suspendedUntil > :now " +
           "AND cdr.reinstatedAt IS NULL " +
           "AND cdr.resolved = false")
    List<CustomerDisciplinaryRecord> findCurrentlySuspendedByCustomer(
            @Param("customerId") String customerId,
            @Param("now") LocalDateTime now
    );
}
