version: '3.8'
services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak-savefood
    environment:
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-db.cbqgwoyam2lh.ap-southeast-2.rds.amazonaws.com:3306/keycloakdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: SaveFoodHVNH2025
    command: ["start-dev", "--http-port", "8081", "--hostname-strict=false"]
    ports:
      - "8081:8081"
    networks:
      - savefood-net

volumes:
  keycloak_data:

networks:
  savefood-net:
    driver: bridge
