package com.example.backend.dto.request;

import jakarta.validation.constraints.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;

@Data
public class ProductVariantRequest {

    @NotBlank(message = "Variant name is required")
    @Size(max = 200, message = "Variant name must not exceed 200 characters")
    private String name;

    // SKU is auto-generated by the system
    // Format: {SUPPLIER_CODE}-{CATEGORY_CODE}-{PRODUCT_ABBR}-{VARIANT_ABBR}-{UNIQUE_SUFFIX}

    @NotNull(message = "Original price is required")
    @DecimalMin(value = "0.0", inclusive = false, message = "Price must be greater than 0")
    private BigDecimal originalPrice;

    @DecimalMin(value = "0.0", message = "Discount price must be greater than or equal to 0")
    private BigDecimal discountPrice;

    private LocalDate manufacturingDate;

    @NotNull(message = "Expiry date is required")
    @Future(message = "Expiry date must be in the future")
    private LocalDate expiryDate;
}
