package com.example.backend.entity;

import com.example.backend.entity.enums.CustomerStatus;
import com.example.backend.entity.enums.ViolationAction;
import com.example.backend.entity.enums.ViolationSeverity;
import com.example.backend.entity.enums.ViolationType;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * Unified entity for tracking customer violations and suspension history
 * Replaces CustomerViolation and CustomerSuspensionHistory tables
 */
@Entity
@Table(name = "customer_disciplinary_records", indexes = {
    @Index(name = "idx_disciplinary_customer", columnList = "customer_id"),
    @Index(name = "idx_disciplinary_type", columnList = "violationType"),
    @Index(name = "idx_disciplinary_severity", columnList = "severity"),
    @Index(name = "idx_disciplinary_action", columnList = "actionTaken"),
    @Index(name = "idx_disciplinary_resolved", columnList = "resolved"),
    @Index(name = "idx_disciplinary_created", columnList = "createdAt"),
    @Index(name = "idx_disciplinary_suspension", columnList = "suspendedUntil"),
    @Index(name = "idx_disciplinary_customer_resolved", columnList = "customer_id, resolved")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class CustomerDisciplinaryRecord {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "record_id")
    private String recordId;

    // ==================== CUSTOMER REFERENCE ====================
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    // ==================== VIOLATION INFORMATION ====================
    
    /**
     * Type of violation committed
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "violation_type", nullable = false, length = 50)
    private ViolationType violationType;

    /**
     * Severity level of the violation
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "severity", nullable = false, length = 20)
    private ViolationSeverity severity;

    /**
     * Detailed description of the violation
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * Reference to related entity (Order ID, Review ID, Comment ID, etc.)
     */
    @Column(name = "reference_id", length = 36)
    private String referenceId;

    /**
     * Type of the referenced entity
     */
    @Column(name = "reference_type", length = 50)
    private String referenceType; // "ORDER", "REVIEW", "COMMENT", "REPORT"

    // ==================== ACTION TAKEN ====================
    
    /**
     * Action taken in response to the violation
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "action_taken", nullable = false, length = 30)
    private ViolationAction actionTaken;

    // ==================== SUSPENSION TRACKING ====================
    // These fields are populated when actionTaken = TEMPORARY_SUSPENSION or PERMANENT_BAN
    
    /**
     * Customer's status before the disciplinary action
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "previous_status", length = 30)
    private CustomerStatus previousStatus;

    /**
     * Customer's status after the disciplinary action
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "new_status", length = 30)
    private CustomerStatus newStatus;

    /**
     * Reason for status change (combines violation + action)
     */
    @Column(name = "status_change_reason", columnDefinition = "TEXT")
    private String statusChangeReason;

    /**
     * Duration of suspension in days (NULL for permanent ban or warnings)
     */
    @Column(name = "suspension_duration_days")
    private Integer suspensionDurationDays;

    /**
     * When the suspension will end (NULL if not suspended or permanently banned)
     */
    @Column(name = "suspended_until")
    private LocalDateTime suspendedUntil;

    /**
     * When the customer was reinstated (NULL if still suspended)
     */
    @Column(name = "reinstated_at")
    private LocalDateTime reinstatedAt;

    // ==================== ADMIN REVIEW ====================
    
    /**
     * Whether this record was auto-generated by the system
     */
    @Column(name = "is_auto_generated", nullable = false)
    private boolean autoGenerated = true;

    /**
     * Admin who reviewed or created this record
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewed_by_admin_id")
    private Admin reviewedByAdmin;

    /**
     * Additional notes from admin
     */
    @Column(name = "admin_notes", columnDefinition = "TEXT")
    private String adminNotes;

    /**
     * Whether this violation has been resolved
     */
    @Column(name = "is_resolved", nullable = false)
    private boolean resolved = false;

    // ==================== TIMESTAMPS ====================
    
    /**
     * When the violation occurred / record was created
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * When an admin reviewed this record
     */
    @Column(name = "reviewed_at")
    private LocalDateTime reviewedAt;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
        
        // Auto-generate status change reason if not provided
        if (statusChangeReason == null && previousStatus != null && newStatus != null) {
            statusChangeReason = String.format("Vi phạm: %s - Hành động: %s", 
                violationType.getDisplayName(), 
                actionTaken.getDisplayName());
        }
    }
}
