package com.example.backend.entity;

import com.example.backend.entity.enums.CustomerStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * Tracks customer suspension history for pattern analysis
 */
@Entity
@Table(name = "customer_suspension_history")
@Data
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class CustomerSuspensionHistory {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "history_id")
    private String historyId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    @Enumerated(EnumType.STRING)
    @Column(name = "previous_status", nullable = false)
    private CustomerStatus previousStatus;

    @Enumerated(EnumType.STRING)
    @Column(name = "new_status", nullable = false)
    private CustomerStatus newStatus;

    @Column(name = "reason", columnDefinition = "TEXT", nullable = false)
    private String reason;

    @Column(name = "suspension_duration_days")
    private Integer suspensionDurationDays;

    @Column(name = "suspended_until")
    private LocalDateTime suspendedUntil;

    @Column(name = "is_auto_generated", nullable = false)
    private boolean autoGenerated = true;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actioned_by_admin_id")
    private Admin actionedByAdmin;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "reinstated_at")
    private LocalDateTime reinstatedAt;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}
