package com.example.backend.entity;

import com.example.backend.entity.enums.ViolationAction;
import com.example.backend.entity.enums.ViolationSeverity;
import com.example.backend.entity.enums.ViolationType;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * Tracks individual customer violations for automated suspension system
 */
@Entity
@Table(name = "customer_violations")
@Data
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class CustomerViolation {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "violation_id")
    private String violationId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    @Enumerated(EnumType.STRING)
    @Column(name = "violation_type", nullable = false)
    private ViolationType violationType;

    @Enumerated(EnumType.STRING)
    @Column(name = "severity", nullable = false)
    private ViolationSeverity severity;

    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    @Column(name = "reference_id")
    private String referenceId; // Order ID, Review ID, Comment ID, etc.

    @Column(name = "reference_type")
    private String referenceType; // "ORDER", "REVIEW", "COMMENT", "REPORT"

    @Enumerated(EnumType.STRING)
    @Column(name = "action_taken", nullable = false)
    private ViolationAction actionTaken;

    @Column(name = "suspension_until")
    private LocalDateTime suspensionUntil;

    @Column(name = "is_auto_generated", nullable = false)
    private boolean autoGenerated = true;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewed_by_admin_id")
    private Admin reviewedByAdmin;

    @Column(name = "admin_notes", columnDefinition = "TEXT")
    private String adminNotes;

    @Column(name = "is_resolved", nullable = false)
    private boolean resolved = false;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "reviewed_at")
    private LocalDateTime reviewedAt;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}
